### ISSUE TITLE
NSFW dictionary

### ISSUE THREAD

**Issue by sebdeckers** [feross/available#7]
A lot of the words seem porn-related. Why? Not sure they would make good NPM package names. Curious how these words got into the dictionary file.

**Comment by feross** [comment]
I believe the dictionary comes from Google web crawling. It's the top words found on the web. And since `available` only shows the words that have not been registered yet, the porn words will be over-represented since I don't imagine many folks are registering those words.

If you can suggest a list of english words (ordered by most used) that is safe-for-work, I'm happy to use it instead 👍 But it has to be ordered, so something like `an-array-of-english-words` by @zeke won't work, for example, since it's not sorted: https://raw.githubusercontent.com/zeke/an-array-of-english-words/master/words.json

**Comment by zeke** [comment]
> If you can suggest a list of english words (ordered by most used)

https://github.com/zeke/subtlex-word-frequencies might help.
